name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout release
      uses: actions/checkout@v3

    - name: Clean temp directory
      run: |
        rm -rf *
        cp -r $GITHUB_WORKSPACE . 
      
    - name: archive drcloud 
      run: tar cvfz ./drcloud.tar.gz *
       
    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./drcloud.tar.gz s3://jhoon-github-action-s3-bucket/archive/
      
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name jhoon-codedeploy-github-action
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name jhoon-codedeploy-github-action-group
        --s3-location bucket=jhoon-codedeploy-github-action,bundleType=tgz,key=archive/drcloud.tar.gz
